### ISSUE TITLE
Warning: Undefined array key “row_html_width”

### ISSUE THREAD

**Issue by elisabettac77** [wolffe/fx-builder#2]
**ISSUE**
I get this error after upgrading to latest release (1.2.0) on ClassicPress 2.1, PHP 8.1. It happens only on one of the pages (https://elica-webservices.it/classicpress-resources/).

Warning: Undefined array key “row_html_width” in /data/vhosts/elica-webservices.it/httpdocs/wp-content/plugins/fx-builder/includes/builder/class-functions.php on line 261

**EXPECTED BEHAVIOR**

No error should be triggered

**UNDERLYING PROBLEM**
the code is trying to access a key named row_html_width from an array element in $rows_data but that key doesn't exist for the specific row being processed ($row_id)

**Comment by wolffe** [comment]
I know, I fixed it and I will soon push an updated version.

**Comment by elisabettac77** [comment]
updated, error still shows

![Schermata del 2024-06-13 18-37-52](https://github.com/wolffe/fx-builder/assets/146635386/47c10978-f0e8-4056-858c-9b3d8f6fe077)

**Comment by wolffe** [comment]
Can you manually update using this version?

https://getbutterfly.com/static/fx-builder-1.2.1.1.zip

**Comment by elisabettac77** [comment]
solved with this last version.

**Comment by wolffe** [comment]
Perfect! Closing issue.
